#!/usr/bin/env python3

# For retrospective experiments
# This script verifies the "Keyword-filter accuracy" statements reported in the results
# section: the size of the flagged set, the precision census over every flagged object,
# and a recall probe that looks for firmware payloads by file signature rather than by
# keyword. Every number printed under "VERIFICATION" is compared against the value
# claimed in the paper, so a changed dataset or classifier shows up as a MISMATCH.
#
# HOW TO RUN
#
#   Reproduce the figures reported in the paper (unencrypted HTTP corpus, the default):
#     python3 src/keyword_filter_accuracy.py
#
#   Same thing, stating the corpus explicitly:
#     python3 src/keyword_filter_accuracy.py retrospective/dataset_extracted/iot-data_http
#
#   Encrypted TLS corpus (verification is skipped: the reported figures are HTTP-only):
#     python3 src/keyword_filter_accuracy.py retrospective/dataset_extracted/iot-data_tls
#
#   List more devices in the per-device breakdown:
#     python3 src/keyword_filter_accuracy.py --top 20
#
# The run takes a few seconds and needs no arguments when the dataset sits in its usual
# place inside this repository.
#
# The input directory should contain the file_metadata.pickle and bin_results.json files
# generated by the analysis script, alongside the per-UUID directories of extracted
# objects. Object paths inside bin_results.json refer to the original capture host, so
# they are re-anchored to the input directory before reading.

import os
import re
import sys
import json
import pickle
import argparse
import time
from collections import Counter, defaultdict

# Track execution time
start_time = time.perf_counter()

# Constants
PICKLE_FILE_CONST = "file_metadata.pickle"
ANAL_RESULTS_CONST = "bin_results.json"
UPDATE_KEYS = ["update", "upgrade", "firmware", "software", "download"]
READ_LIMIT = 2_000_000  # bytes of each object inspected for the precision census

# Precision categories, applied in order: the first matching rule wins, so the list
# encodes precedence. Category A is deliberately narrowest.
PRECISION_RULES = [
    ("A firmware-download reference",
     lambda t: "amcrest-firmwares" in t or "Download_Site" in t),
    ("B update-status message",
     lambda t: "swupdate" in t or "noupdates" in t or "updatestate" in t.lower()),
    ("C version or capability information",
     lambda t: "GetSystemUpdateID" in t or re.search(
         r"firmwareVersion|software-version|softwareVersion|fw_ver|firmware_version",
         t, re.I) is not None),
    ("D OCSP certificate-status field",
     lambda t: "thisUpdate" in t or "nextUpdate" in t),
]
RESIDUAL_LABEL = "E unrelated to updates"

# libmagic signatures of payloads that are shaped like firmware or an installable
# package. Used for the recall probe: these are identified without any keyword.
FIRMWARE_MAGIC = re.compile(
    r"squashfs|jffs2|cramfs|ubifs|u-boot|uImage|Linux kernel|ELF |"
    r"Android package|Debian binary|ISO 9660|initrd|romfs",
    re.I)

# Values asserted in the paper, checked at the end of the run.
CLAIMS = {
    "extracted objects": 655167,
    "flagged objects": 1731,
    "A firmware-download reference": 71,
    "B update-status message": 1059,
    "C version or capability information": 426,
    "E unrelated to updates": 173,
    "firmware payloads present": 6,
    "firmware payloads flagged": 0,
}

# The dataset normally sits inside this repository, so the corpus reported in the paper
# is the default and the script runs with no arguments at all.
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_INPUT = os.path.join(REPO_ROOT, "retrospective", "dataset_extracted",
                             "iot-data_http")

# Parse arguments
parser = argparse.ArgumentParser(
    description='Verify the keyword-filter precision and recall figures',
    epilog="examples:\n"
           "  python3 src/keyword_filter_accuracy.py\n"
           "  python3 src/keyword_filter_accuracy.py "
           "retrospective/dataset_extracted/iot-data_tls\n"
           "  python3 src/keyword_filter_accuracy.py --top 20\n",
    formatter_class=argparse.RawDescriptionHelpFormatter)
parser.add_argument('input_dir', type=str, nargs='?', default=DEFAULT_INPUT,
                    help='Directory containing bin_results.json, file_metadata.pickle '
                         'and the per-UUID object directories '
                         '(default: %(default)s)')
parser.add_argument('--top', type=int, default=10,
                    help='Number of devices to list in the per-device breakdown')
args = parser.parse_args()

for required in (ANAL_RESULTS_CONST, PICKLE_FILE_CONST):
    if not os.path.isfile(os.path.join(args.input_dir, required)):
        sys.exit(f"[!] {required} not found in {args.input_dir}\n"
                 f"    Pass the corpus directory explicitly, e.g.\n"
                 f"    python3 src/keyword_filter_accuracy.py "
                 f"retrospective/dataset_extracted/iot-data_http")

print(f"[+] Corpus: {args.input_dir}")

# Load analysis results
with open(os.path.join(args.input_dir, ANAL_RESULTS_CONST), 'r') as f:
    results_data = json.load(f)
    print("[+] Loaded analysis JSON")

# Load device metadata
with open(os.path.join(args.input_dir, PICKLE_FILE_CONST), 'rb') as f:
    device_metadata = pickle.load(f)
    print("[+] Loaded device metadata")

# Helper to get device by UUID.
# Note: in this metadata the 'region' field carries the device name (e.g. wemo-plug)
# while the 'device' field carries the trigger action (e.g. android_lan_on).
device_by_uuid = {d['uuid']: d for d in device_metadata}


def device_name(uuid):
    meta = device_by_uuid.get(uuid)
    return meta.get('region', 'unknown') if meta else 'unknown'


def object_path(uuid, recorded_path):
    """Re-anchor a path recorded on the capture host to the input directory."""
    return os.path.join(args.input_dir, uuid, os.path.basename(recorded_path))


# Counters
observed = {}
extracted_total = 0
flagged = []            # (uuid, path) of every object with a keyword flag
keyword_counter = Counter()
device_counter = Counter()
firmware_payloads = []  # (uuid, path, magic, flagged) for every firmware-shaped object

# Pass 1: walk the analysis results
print("[+] Scanning extracted objects")
for entry in results_data.get("results", []):
    uuid = entry.get("uuid")
    for file_info in entry.get("file_infos", []):
        extracted_total += 1
        update_meta = file_info.get("update_meta", {})
        hits = [k for k in UPDATE_KEYS if update_meta.get(k) is True]
        path = object_path(uuid, file_info.get("file", ""))

        if hits:
            for key in hits:
                keyword_counter[key] += 1
            device_counter[device_name(uuid)] += 1
            flagged.append((uuid, path))

        magic = file_info.get("magic") or ""
        if FIRMWARE_MAGIC.search(magic):
            firmware_payloads.append((uuid, path, magic, bool(hits)))

observed["extracted objects"] = extracted_total
observed["flagged objects"] = len(flagged)

print("\n=== Flagged set ===")
print(f"Extracted objects: {extracted_total:,}")
pct = 100 * len(flagged) / extracted_total if extracted_total else 0
print(f"Flagged objects:   {len(flagged):,} ({pct:.2f}%)")
print("Keyword hits:", dict(keyword_counter))

# Pass 2: precision census over every flagged object
print("\n[+] Classifying every flagged object (census, not a sample)")
categories = Counter()
residual_examples = []
unreadable = 0

for uuid, path in flagged:
    try:
        with open(path, 'rb') as fh:
            content = fh.read(READ_LIMIT).decode('utf8', 'ignore')
    except OSError:
        unreadable += 1
        continue

    for label, rule in PRECISION_RULES:
        if rule(content):
            categories[label] += 1
            break
    else:
        categories[RESIDUAL_LABEL] += 1
        residual_examples.append(os.path.basename(path))

classified = sum(categories.values())
print("\n=== Precision census ===")
for label in sorted(categories):
    share = 100 * categories[label] / classified if classified else 0
    print(f"  {label:38s} {categories[label]:6,d}  {share:5.1f}%")
print(f"  {'total classified':38s} {classified:6,d}")
if unreadable:
    print(f"  [!] {unreadable} flagged objects could not be read from {args.input_dir}")
if residual_examples:
    print("  residual sample:", ", ".join(sorted(set(residual_examples))[:6]))

for label in categories:
    observed[label] = categories[label]

# Pass 3: recall probe. Firmware payloads are identified by file signature, which is
# independent of the keyword filter, so this measures what the filter did not catch.
missed = [p for p in firmware_payloads if not p[3]]
observed["firmware payloads present"] = len(firmware_payloads)
observed["firmware payloads flagged"] = len(firmware_payloads) - len(missed)

print("\n=== Recall probe (firmware payloads by file signature) ===")
print(f"Firmware-shaped payloads present: {len(firmware_payloads)}")
print(f"  detected by keyword filter:     {len(firmware_payloads) - len(missed)}")
print(f"  MISSED by keyword filter:       {len(missed)}")
if firmware_payloads:
    print()
    print(f"  {'size':>10s}  {'device':22s} {'flagged':7s} {'object':32s} signature")
    for uuid, path, magic, was_flagged in sorted(
            firmware_payloads, key=lambda p: p[2]):
        try:
            size = os.path.getsize(path)
            size_str = f"{size:,}"
        except OSError:
            size_str = "n/a"
        print(f"  {size_str:>10s}  {device_name(uuid)[:22]:22s} "
              f"{'yes' if was_flagged else 'NO':7s} {os.path.basename(path)[:32]:32s} "
              f"{magic[:48]}")

# Per-device breakdown of the flagged set
print(f"\n=== Devices with most flagged objects (top {args.top}) ===")
for name, count in device_counter.most_common(args.top):
    share = 100 * count / len(flagged) if flagged else 0
    print(f"  {name:26s} {count:6,d}  {share:5.1f}%")

# Verification against the values reported in the paper. The reported figures describe
# the unencrypted HTTP corpus, so the comparison is skipped for any other input.
if "http" not in os.path.basename(os.path.normpath(args.input_dir)).lower():
    print("\n[!] Reported figures cover the HTTP corpus only; verification skipped.")
    end_time = time.perf_counter()
    print(f"\n[+] Script finished in {end_time - start_time:.2f} seconds")
    raise SystemExit(0)

print("\n=== VERIFICATION against reported figures ===")
mismatches = 0
for key, claimed in CLAIMS.items():
    actual = observed.get(key)
    if actual is None:
        print(f"  {key:38s} claimed {claimed:>8,}   NOT MEASURED")
        mismatches += 1
    elif actual == claimed:
        print(f"  {key:38s} claimed {claimed:>8,}   observed {actual:>8,}   OK")
    else:
        print(f"  {key:38s} claimed {claimed:>8,}   observed {actual:>8,}   MISMATCH")
        mismatches += 1
print(f"\n{'All reported figures reproduce.' if not mismatches else f'{mismatches} figure(s) do not reproduce.'}")

# Execution time
end_time = time.perf_counter()
print(f"\n[+] Script finished in {end_time - start_time:.2f} seconds")
